# Generated by Django 3.1.7 on 2021-04-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210407_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Blog Description',
            new_name='BlogDescription',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Date Created',
            new_name='DateCreated',
        ),
    ]
