# Generated by Django 3.1.7 on 2021-04-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210407_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='DateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='BlogDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Title',
            new_name='title',
        ),
    ]
