# Generated by Django 3.1.7 on 2021-04-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210407_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(verbose_name='Date Created'),
        ),
    ]
